### ISSUE TITLE
Failing all browser tests at testling.com

### ISSUE THREAD

**Issue by mulhoon** [leonidas/transparency#129]
The project is currently failing in all browsers at https://ci.testling.com/leonidas/transparency
```
not ok 1 Error: Expected ';' on line 1
```

**Comment by pyykkis** [comment]
Cool, so testling is finally up and running again, thanks for letting me know. It was down at least two months or so. I'll take a look.

**Comment by pyykkis** [comment]
D'oh, it seems testling-ci service is still down, and just gives time outs for the github webhooks. The last succesful (but failed) run is from October, even though I recently made some readme changes.

I'm moving browser based CI to BrowserStack, or to some other service. In case you happen to know good candidates, please let me know.

For now, I removed testling badge from the README.
