### ISSUE TITLE
html tag in JSON is not parsed properly

### ISSUE THREAD

**Issue by junpos** [leonidas/transparency#133]
Hi leonidas, I'm having problem with parsing JSON data with this awesome plugin.
The example here with html tag is working fine as the object value is single-quoted.

    var hello = {
      greeting: 'Hello',
      name:     '<b>world!</b>'
    };

    $('#template').render(hello);

But the problem arise when data has html tag as values. 
Let's say we have an external **sample.json** file, 

    //sample.json
    {
      "greeting" : "Hello",
      "name" :     "<b>world!</b>"
    }

    //app.js
    $.getJSON("sample.json", function(json){
        $('#template').render(hello);//won't work
    });

In this scenario, the tag **\<b>** is not parsed as html tag but plain text. And the result will be
#### Hello \<b>world!\</b>####

How could I use html tag in JSON file and use them with transparency?

**Comment by rikukissa** [comment]
Hi! Check this out: https://github.com/leonidas/transparency/issues/10
It seems that you can accomplish this with directive that just returns the value as it is.
[Code example](http://codepen.io/rikukissa/pen/rVyMVr)

**Comment by junpos** [comment]
Thank you so much **rikukissa**.
Your example was perfect for me but I had some hard time with creating dynamics directives, but I could resolve the problem with IIFE.
Again, I really appreciate your help.

    function extractByLang(dictionary, lang) {
      var data = {};
      var directives = {};

      for (var name in dictionary) {
        var val = dictionary[name][lang] ? dictionary[name][lang] : dictionary[name]['en'];
        data[name] = val;
        if (val.search('<') !== -1) {//html tag included       
          (function(copy){
            directives[name] = {
              html : function(){
                return copy;
              }
            };
          })(val);
        }
      }

      return {
        data: data,
        directives: directives
      };
    }
