### ISSUE TITLE
dist/transparency.js refers to ./helpers which doesn't exist

### ISSUE THREAD

**Issue by bryanjswift** [leonidas/transparency#138]
The files in `dist` do not include the files from `lib` inline so when attempting to run them through something like [browserify](http://browserify.org) the parsing fails because the files aren't found. I'd recommend either:

1. Include these dependencies inline within the files in the `dist` folder or
2. Leaving `main` in `package.json` as the default `index.js` which then resolves dependencies correctly

**Comment by Ghosh** [comment]
+1 for this
